// <auto-generated />
using System;
using LiminoAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LiminoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190521095120_ExerciseLevelAndCategoryUpdate")]
    partial class ExerciseLevelAndCategoryUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LiminoAPI.Data.Models.Answer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AudioUrl");

                    b.Property<bool>("Correct");

                    b.Property<long>("ExerciseId");

                    b.Property<string>("ImageUrl");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.ToTable("Answers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Correct = false,
                            ExerciseId = 1L,
                            ImageUrl = "Knop juist.png"
                        },
                        new
                        {
                            Id = 2L,
                            Correct = true,
                            ExerciseId = 1L,
                            ImageUrl = "Knop niet goed.png"
                        },
                        new
                        {
                            Id = 3L,
                            Correct = false,
                            ExerciseId = 2L,
                            ImageUrl = "Knop juist.png"
                        },
                        new
                        {
                            Id = 4L,
                            Correct = true,
                            ExerciseId = 2L,
                            ImageUrl = "Knop niet goed.png"
                        },
                        new
                        {
                            Id = 5L,
                            AudioUrl = "de_appel.mp3",
                            Correct = true,
                            ExerciseId = 3L,
                            ImageUrl = "appel.jpg"
                        },
                        new
                        {
                            Id = 6L,
                            AudioUrl = "de_banaan.mp3",
                            Correct = false,
                            ExerciseId = 3L,
                            ImageUrl = "banaan.jpg"
                        },
                        new
                        {
                            Id = 7L,
                            AudioUrl = "de_sinaasappel.mp3",
                            Correct = false,
                            ExerciseId = 3L,
                            ImageUrl = "sinaasappel.jpg"
                        },
                        new
                        {
                            Id = 8L,
                            AudioUrl = "de_aardbei.mp3",
                            Correct = false,
                            ExerciseId = 3L,
                            ImageUrl = "aardbei.jpg"
                        },
                        new
                        {
                            Id = 9L,
                            AudioUrl = "de_druiven.mp3",
                            Correct = false,
                            ExerciseId = 3L,
                            ImageUrl = "druiven.jpg"
                        },
                        new
                        {
                            Id = 10L,
                            AudioUrl = "de_kiwi.mp3",
                            Correct = false,
                            ExerciseId = 3L,
                            ImageUrl = "kiwi.jpg"
                        },
                        new
                        {
                            Id = 11L,
                            AudioUrl = "de_komkommer.mp3",
                            Correct = false,
                            ExerciseId = 3L,
                            ImageUrl = "komkommer.jpg"
                        },
                        new
                        {
                            Id = 12L,
                            AudioUrl = "de_tomaat.mp3",
                            Correct = false,
                            ExerciseId = 3L,
                            ImageUrl = "tomaat.jpg"
                        },
                        new
                        {
                            Id = 13L,
                            AudioUrl = "de_wortel.mp3",
                            Correct = false,
                            ExerciseId = 3L,
                            ImageUrl = "wortel.jpg"
                        },
                        new
                        {
                            Id = 14L,
                            AudioUrl = "taart.mp3",
                            Correct = false,
                            ExerciseId = 4L,
                            ImageUrl = "taart.jpg"
                        },
                        new
                        {
                            Id = 15L,
                            AudioUrl = "koekjes.mp3",
                            Correct = true,
                            ExerciseId = 4L,
                            ImageUrl = "koekjes.jpg"
                        },
                        new
                        {
                            Id = 16L,
                            AudioUrl = "muffins.mp3",
                            Correct = false,
                            ExerciseId = 4L,
                            ImageUrl = "muffin.jpg"
                        },
                        new
                        {
                            Id = 17L,
                            AudioUrl = "brood.mp3",
                            Correct = false,
                            ExerciseId = 4L,
                            ImageUrl = "brood.jpg"
                        },
                        new
                        {
                            Id = 18L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = false,
                            ExerciseId = 5L,
                            ImageUrl = "eten-en-drinken.jpg"
                        },
                        new
                        {
                            Id = 19L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = false,
                            ExerciseId = 5L,
                            ImageUrl = "eten-en-drinken.jpg"
                        },
                        new
                        {
                            Id = 20L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = false,
                            ExerciseId = 5L,
                            ImageUrl = "eten-en-drinken.jpg"
                        },
                        new
                        {
                            Id = 21L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = false,
                            ExerciseId = 5L,
                            ImageUrl = "eten-en-drinken.jpg"
                        },
                        new
                        {
                            Id = 22L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = false,
                            ExerciseId = 6L,
                            ImageUrl = "eten-en-drinken.jpg"
                        },
                        new
                        {
                            Id = 23L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = false,
                            ExerciseId = 6L,
                            ImageUrl = "eten-en-drinken.jpg"
                        },
                        new
                        {
                            Id = 24L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = false,
                            ExerciseId = 6L,
                            ImageUrl = "eten-en-drinken.jpg"
                        },
                        new
                        {
                            Id = 25L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = false,
                            ExerciseId = 7L,
                            ImageUrl = "eten-en-drinken.jpg"
                        },
                        new
                        {
                            Id = 26L,
                            AudioUrl = "wieBenJijAudio1.wav",
                            Correct = true,
                            ExerciseId = 7L,
                            ImageUrl = "eten-en-drinken.jpg"
                        });
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.Audio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoryId");

                    b.Property<string>("FragmentUrl");

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Audios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 22L,
                            FragmentUrl = "wieBenJijAudio1.wav",
                            ImageUrl = "wieBenJijAudio1.jpg",
                            Name = "wieBenJijAudio1"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 22L,
                            FragmentUrl = "wieBenJijAudio2.wav",
                            ImageUrl = "wieBenJijAudio2.jpg",
                            Name = "wieBenJijAudio2"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 22L,
                            FragmentUrl = "wieBenJijAudio2.wav",
                            ImageUrl = "wieBenJijAudio3.jpg",
                            Name = "wieBenJijAudio3"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 23L,
                            FragmentUrl = "één.mp3",
                            ImageUrl = "één.jpg",
                            Name = "één"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 23L,
                            FragmentUrl = "twee.mp3",
                            ImageUrl = "twee.jpg",
                            Name = "twee"
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 23L,
                            FragmentUrl = "drie.mp3",
                            ImageUrl = "drie.jpg",
                            Name = "drie"
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 24L,
                            FragmentUrl = "zonneschijn.mp3",
                            ImageUrl = "zonneschijn.jpg",
                            Name = "zonneschijn"
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 24L,
                            FragmentUrl = "regen.mp3",
                            ImageUrl = "regen.jpg",
                            Name = "regen"
                        },
                        new
                        {
                            Id = 9L,
                            CategoryId = 24L,
                            FragmentUrl = "bewolkt.mp3",
                            ImageUrl = "bewolkt.jpg",
                            Name = "bewolkt"
                        },
                        new
                        {
                            Id = 10L,
                            CategoryId = 25L,
                            FragmentUrl = "twaalfUur.mp3",
                            ImageUrl = "twaalfUur.jpg",
                            Name = "twaalfUur"
                        },
                        new
                        {
                            Id = 11L,
                            CategoryId = 25L,
                            FragmentUrl = "kwartVoorTwee.mp3",
                            ImageUrl = "kwartVoorTwee.jpg",
                            Name = "kwartVoorTwee"
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 25L,
                            FragmentUrl = "zesUur.mp3",
                            ImageUrl = "zesUur.jpg",
                            Name = "zesUur"
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 26L,
                            FragmentUrl = "schoolAudio1.mp3",
                            ImageUrl = "schoolAudio1.jpg",
                            Name = "schoolAudio1"
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 26L,
                            FragmentUrl = "schoolAudio2.mp3",
                            ImageUrl = "schoolAudio2.jpg",
                            Name = "schoolAudio2"
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 26L,
                            FragmentUrl = "schoolAudio3.mp3",
                            ImageUrl = "schoolAudio3.jpg",
                            Name = "schoolAudio3"
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 27L,
                            FragmentUrl = "amsterdam.mp3",
                            ImageUrl = "amsterdam.jpg",
                            Name = "amsterdam"
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 27L,
                            FragmentUrl = "parijs.mp3",
                            ImageUrl = "parijs.jpg",
                            Name = "parijs"
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 27L,
                            FragmentUrl = "brussel.mp3",
                            ImageUrl = "brussel.jpg",
                            Name = "brussel"
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 28L,
                            FragmentUrl = "afspraakAudio1.mp3",
                            ImageUrl = "afspraakAudio1.jpg",
                            Name = "afspraakAudio1"
                        },
                        new
                        {
                            Id = 20L,
                            CategoryId = 28L,
                            FragmentUrl = "afspraakAudio2.mp3",
                            ImageUrl = "afspraakAudio2.jpg",
                            Name = "afspraakAudio2"
                        },
                        new
                        {
                            Id = 21L,
                            CategoryId = 28L,
                            FragmentUrl = "afspraakAudio.mp3",
                            ImageUrl = "afspraakAudio3.jpg",
                            Name = "afspraakAudio3"
                        },
                        new
                        {
                            Id = 22L,
                            CategoryId = 29L,
                            FragmentUrl = "vraagAudio1.mp3",
                            ImageUrl = "vraagAudio1.jpg",
                            Name = "vraagAudio1"
                        },
                        new
                        {
                            Id = 23L,
                            CategoryId = 29L,
                            FragmentUrl = "vraagAudio2.mp3",
                            ImageUrl = "vraagAudio2.jpg",
                            Name = "vraagAudio2"
                        },
                        new
                        {
                            Id = 24L,
                            CategoryId = 29L,
                            FragmentUrl = "vraagAudio3.mp3",
                            ImageUrl = "vraagAudio3.jpg",
                            Name = "vraagAudio3"
                        },
                        new
                        {
                            Id = 25L,
                            CategoryId = 30L,
                            FragmentUrl = "de_sinaasappel.mp3",
                            ImageUrl = "sinaasappel.jpg",
                            Name = "appelsien"
                        },
                        new
                        {
                            Id = 26L,
                            CategoryId = 30L,
                            FragmentUrl = "de_banaan.mp3",
                            ImageUrl = "banaan.jpg",
                            Name = "banaan"
                        },
                        new
                        {
                            Id = 27L,
                            CategoryId = 30L,
                            FragmentUrl = "de_appel.mp3",
                            ImageUrl = "appel.jpg",
                            Name = "appel"
                        },
                        new
                        {
                            Id = 28L,
                            CategoryId = 31L,
                            FragmentUrl = "broek.mp3",
                            ImageUrl = "broek.jpg",
                            Name = "broek"
                        },
                        new
                        {
                            Id = 29L,
                            CategoryId = 31L,
                            FragmentUrl = "trui.mp3",
                            ImageUrl = "trui.jpg",
                            Name = "trui"
                        },
                        new
                        {
                            Id = 30L,
                            CategoryId = 31L,
                            FragmentUrl = "schoenen.mp3",
                            ImageUrl = "schoenen.jpg",
                            Name = "schoenen"
                        },
                        new
                        {
                            Id = 31L,
                            CategoryId = 32L,
                            FragmentUrl = "winkelAudio1.mp3",
                            ImageUrl = "winkelAudio1.jpg",
                            Name = "winkelAudio1"
                        },
                        new
                        {
                            Id = 32L,
                            CategoryId = 32L,
                            FragmentUrl = "winkelAudio2.mp3",
                            ImageUrl = "winkelAudio2.jpg",
                            Name = "winkelAudio2"
                        },
                        new
                        {
                            Id = 33L,
                            CategoryId = 32L,
                            FragmentUrl = "winkelAudio3.mp3",
                            ImageUrl = "winkelAudio3.jpg",
                            Name = "winkelAudio3"
                        },
                        new
                        {
                            Id = 34L,
                            CategoryId = 33L,
                            FragmentUrl = "stoel.mp3",
                            ImageUrl = "stoel.jpg",
                            Name = "stoel"
                        },
                        new
                        {
                            Id = 35L,
                            CategoryId = 33L,
                            FragmentUrl = "tafel.mp3",
                            ImageUrl = "tafel.jpg",
                            Name = "tafel"
                        },
                        new
                        {
                            Id = 36L,
                            CategoryId = 33L,
                            FragmentUrl = "kast.mp3",
                            ImageUrl = "kast.jpg",
                            Name = "kast"
                        },
                        new
                        {
                            Id = 37L,
                            CategoryId = 34L,
                            FragmentUrl = "bloedneus.mp3",
                            ImageUrl = "bloedneus.jpg",
                            Name = "bloedneus"
                        },
                        new
                        {
                            Id = 38L,
                            CategoryId = 34L,
                            FragmentUrl = "naald.mp3",
                            ImageUrl = "naald.jpg",
                            Name = "naald"
                        },
                        new
                        {
                            Id = 39L,
                            CategoryId = 34L,
                            FragmentUrl = "medicijn.mp3",
                            ImageUrl = "medicijn.jpg",
                            Name = "medicijn"
                        },
                        new
                        {
                            Id = 40L,
                            CategoryId = 35L,
                            FragmentUrl = "verkeerslicht.mp3",
                            ImageUrl = "verkeerslicht.jpg",
                            Name = "verkeerslicht"
                        },
                        new
                        {
                            Id = 41L,
                            CategoryId = 35L,
                            FragmentUrl = "auto.mp3",
                            ImageUrl = "auto.jpg",
                            Name = "auto"
                        },
                        new
                        {
                            Id = 42L,
                            CategoryId = 35L,
                            FragmentUrl = "fiets.mp3",
                            ImageUrl = "fiets.jpg",
                            Name = "fiets"
                        },
                        new
                        {
                            Id = 43L,
                            CategoryId = 36L,
                            FragmentUrl = "bouwvakker.mp3",
                            ImageUrl = "bouwvakker.jpg",
                            Name = "bouwvakker"
                        },
                        new
                        {
                            Id = 44L,
                            CategoryId = 36L,
                            FragmentUrl = "leerkracht.mp3",
                            ImageUrl = "leerkracht.jpg",
                            Name = "leerkracht"
                        },
                        new
                        {
                            Id = 45L,
                            CategoryId = 36L,
                            FragmentUrl = "dokter.mp3",
                            ImageUrl = "dokter.jpg",
                            Name = "dokter"
                        },
                        new
                        {
                            Id = 46L,
                            CategoryId = 37L,
                            FragmentUrl = "fietsen.mp3",
                            ImageUrl = "fietsen.jpg",
                            Name = "fietsen"
                        },
                        new
                        {
                            Id = 47L,
                            CategoryId = 37L,
                            FragmentUrl = "voetballen.mp3",
                            ImageUrl = "voetballen.jpg",
                            Name = "voetballen"
                        },
                        new
                        {
                            Id = 48L,
                            CategoryId = 37L,
                            FragmentUrl = "zwemmen.mp3",
                            ImageUrl = "zwemmen.jpg",
                            Name = "zwemmen"
                        },
                        new
                        {
                            Id = 49L,
                            CategoryId = 38L,
                            FragmentUrl = "baby.mp3",
                            ImageUrl = "baby.jpg",
                            Name = "baby"
                        },
                        new
                        {
                            Id = 50L,
                            CategoryId = 38L,
                            FragmentUrl = "kleuter.mp3",
                            ImageUrl = "kleuter.jpg",
                            Name = "kleuter"
                        },
                        new
                        {
                            Id = 51L,
                            CategoryId = 38L,
                            FragmentUrl = "tiener.mp3",
                            ImageUrl = "tiener.jpg",
                            Name = "tiener"
                        },
                        new
                        {
                            Id = 52L,
                            CategoryId = 39L,
                            FragmentUrl = "blij.mp3",
                            ImageUrl = "blij.jpg",
                            Name = "blij"
                        },
                        new
                        {
                            Id = 53L,
                            CategoryId = 39L,
                            FragmentUrl = "verdrietig.mp3",
                            ImageUrl = "verdrietig.jpg",
                            Name = "verdrietig"
                        },
                        new
                        {
                            Id = 54L,
                            CategoryId = 39L,
                            FragmentUrl = "bang.mp3",
                            ImageUrl = "bang.jpg",
                            Name = "bang"
                        },
                        new
                        {
                            Id = 55L,
                            CategoryId = 40L,
                            FragmentUrl = "nieuwLievenAudio1.mp3",
                            ImageUrl = "nieuwLevenAudio1.jpg",
                            Name = "nieuwLevenAudio1"
                        },
                        new
                        {
                            Id = 56L,
                            CategoryId = 40L,
                            FragmentUrl = "nieuwLievenAudio2.mp3",
                            ImageUrl = "nieuwLevenAudio2.jpg",
                            Name = "nieuwLevenAudio2"
                        },
                        new
                        {
                            Id = 57L,
                            CategoryId = 40L,
                            FragmentUrl = "nieuwLievenAudio3.mp3",
                            ImageUrl = "nieuwLevenAudio3.jpg",
                            Name = "nieuwLevenAudio3"
                        },
                        new
                        {
                            Id = 58L,
                            CategoryId = 41L,
                            FragmentUrl = "identiteitskaart.mp3",
                            ImageUrl = "identiteitskaart.jpg",
                            Name = "identiteitskaart"
                        },
                        new
                        {
                            Id = 59L,
                            CategoryId = 41L,
                            FragmentUrl = "rijbewijs.mp3",
                            ImageUrl = "rijbewijs.jpg",
                            Name = "rijbewijs"
                        },
                        new
                        {
                            Id = 60L,
                            CategoryId = 41L,
                            FragmentUrl = "bankkaart.mp3",
                            ImageUrl = "bankkaart.jpg",
                            Name = "bankkaart"
                        });
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ImageUrl = "wie-ben-jij.jpg",
                            Name = "Wie ben jij?"
                        },
                        new
                        {
                            Id = 2L,
                            ImageUrl = "cijfers.jpg",
                            Name = "Cijfers"
                        },
                        new
                        {
                            Id = 3L,
                            ImageUrl = "het-weer.png",
                            Name = "Het weer"
                        },
                        new
                        {
                            Id = 4L,
                            ImageUrl = "tijd.jpg",
                            Name = "Tijd"
                        },
                        new
                        {
                            Id = 5L,
                            ImageUrl = "school.jpg",
                            Name = "School"
                        },
                        new
                        {
                            Id = 6L,
                            ImageUrl = "plaatsen.jpg",
                            Name = "Plaatsen / Ga je mee"
                        },
                        new
                        {
                            Id = 7L,
                            ImageUrl = "afspraak.jpg",
                            Name = "Afspraak"
                        },
                        new
                        {
                            Id = 8L,
                            ImageUrl = "vragen.jpg",
                            Name = "Vragen"
                        },
                        new
                        {
                            Id = 9L,
                            ImageUrl = "eten-en-drinken.jpg",
                            Name = "Eten en drinken"
                        },
                        new
                        {
                            Id = 10L,
                            ImageUrl = "kleding.jpg",
                            Name = "Kleding"
                        },
                        new
                        {
                            Id = 11L,
                            ImageUrl = "winkel.jpg",
                            Name = "Winkel"
                        },
                        new
                        {
                            Id = 12L,
                            ImageUrl = "wonen.jpg",
                            Name = "Wonen"
                        },
                        new
                        {
                            Id = 13L,
                            ImageUrl = "gezondheid.jpg",
                            Name = "Gezondheid"
                        },
                        new
                        {
                            Id = 14L,
                            ImageUrl = "verkeer.jpg",
                            Name = "Verkeer"
                        },
                        new
                        {
                            Id = 15L,
                            ImageUrl = "werk.jpg",
                            Name = "Werk"
                        },
                        new
                        {
                            Id = 16L,
                            ImageUrl = "vrije-tijd.png",
                            Name = "Vrije tijd"
                        },
                        new
                        {
                            Id = 17L,
                            ImageUrl = "kinderen.jpg",
                            Name = "Kinderen"
                        },
                        new
                        {
                            Id = 18L,
                            ImageUrl = "mening-gevoel.jpg",
                            Name = "Mening / gevoel"
                        },
                        new
                        {
                            Id = 19L,
                            ImageUrl = "nieuw-leven.jpg",
                            Name = "Nieuw leven"
                        },
                        new
                        {
                            Id = 20L,
                            ImageUrl = "documenten.jpg",
                            Name = "Documenten"
                        },
                        new
                        {
                            Id = 21L,
                            ImageUrl = "limino-filmpjes.jpg",
                            Name = "LiMiNo-filmpjes"
                        },
                        new
                        {
                            Id = 22L,
                            ImageUrl = "wie-ben-jij.jpg",
                            Name = "Wie ben jij?"
                        },
                        new
                        {
                            Id = 23L,
                            ImageUrl = "cijfers.jpg",
                            Name = "Cijfers"
                        },
                        new
                        {
                            Id = 24L,
                            ImageUrl = "het-weer.png",
                            Name = "Het weer"
                        },
                        new
                        {
                            Id = 25L,
                            ImageUrl = "tijd.jpg",
                            Name = "Tijd"
                        },
                        new
                        {
                            Id = 26L,
                            ImageUrl = "school.jpg",
                            Name = "School"
                        },
                        new
                        {
                            Id = 27L,
                            ImageUrl = "plaatsen.jpg",
                            Name = "Plaatsen / Ga je mee"
                        },
                        new
                        {
                            Id = 28L,
                            ImageUrl = "afspraak.jpg",
                            Name = "Afspraak"
                        },
                        new
                        {
                            Id = 29L,
                            ImageUrl = "vragen.jpg",
                            Name = "Vragen"
                        },
                        new
                        {
                            Id = 30L,
                            ImageUrl = "eten-en-drinken.jpg",
                            Name = "Eten en drinken"
                        },
                        new
                        {
                            Id = 31L,
                            ImageUrl = "kleding.jpg",
                            Name = "Kleding"
                        },
                        new
                        {
                            Id = 32L,
                            ImageUrl = "winkel.jpg",
                            Name = "Winkel"
                        },
                        new
                        {
                            Id = 33L,
                            ImageUrl = "wonen.jpg",
                            Name = "Wonen"
                        },
                        new
                        {
                            Id = 34L,
                            ImageUrl = "gezondheid.jpg",
                            Name = "Gezondheid"
                        },
                        new
                        {
                            Id = 35L,
                            ImageUrl = "verkeer.jpg",
                            Name = "Verkeer"
                        },
                        new
                        {
                            Id = 36L,
                            ImageUrl = "werk.jpg",
                            Name = "Werk"
                        },
                        new
                        {
                            Id = 37L,
                            ImageUrl = "vrije-tijd.png",
                            Name = "Vrije tijd"
                        },
                        new
                        {
                            Id = 38L,
                            ImageUrl = "kinderen.jpg",
                            Name = "Kinderen"
                        },
                        new
                        {
                            Id = 39L,
                            ImageUrl = "mening-gevoel.jpg",
                            Name = "Mening / gevoel"
                        },
                        new
                        {
                            Id = 40L,
                            ImageUrl = "nieuw-leven.jpg",
                            Name = "Nieuw leven"
                        },
                        new
                        {
                            Id = 41L,
                            ImageUrl = "wie-ben-jij.jpg",
                            Name = "Wie ben jij?"
                        },
                        new
                        {
                            Id = 42L,
                            ImageUrl = "cijfers.jpg",
                            Name = "Cijfers"
                        },
                        new
                        {
                            Id = 43L,
                            ImageUrl = "het-weer.png",
                            Name = "Het weer"
                        },
                        new
                        {
                            Id = 44L,
                            ImageUrl = "tijd.jpg",
                            Name = "Tijd"
                        },
                        new
                        {
                            Id = 45L,
                            ImageUrl = "school.jpg",
                            Name = "School"
                        },
                        new
                        {
                            Id = 46L,
                            ImageUrl = "plaatsen.jpg",
                            Name = "Plaatsen / Ga je mee"
                        },
                        new
                        {
                            Id = 47L,
                            ImageUrl = "afspraak.jpg",
                            Name = "Afspraak"
                        },
                        new
                        {
                            Id = 48L,
                            ImageUrl = "vragen.jpg",
                            Name = "Vragen"
                        },
                        new
                        {
                            Id = 49L,
                            ImageUrl = "eten-en-drinken.jpg",
                            Name = "Eten en drinken"
                        },
                        new
                        {
                            Id = 50L,
                            ImageUrl = "kleding.jpg",
                            Name = "Kleding"
                        },
                        new
                        {
                            Id = 51L,
                            ImageUrl = "winkel.jpg",
                            Name = "Winkel"
                        },
                        new
                        {
                            Id = 52L,
                            ImageUrl = "wonen.jpg",
                            Name = "Wonen"
                        },
                        new
                        {
                            Id = 53L,
                            ImageUrl = "gezondheid.jpg",
                            Name = "Gezondheid"
                        },
                        new
                        {
                            Id = 54L,
                            ImageUrl = "verkeer.jpg",
                            Name = "Verkeer"
                        },
                        new
                        {
                            Id = 55L,
                            ImageUrl = "werk.jpg",
                            Name = "Werk"
                        },
                        new
                        {
                            Id = 56L,
                            ImageUrl = "vrije-tijd.png",
                            Name = "Vrije tijd"
                        },
                        new
                        {
                            Id = 57L,
                            ImageUrl = "kinderen.jpg",
                            Name = "Kinderen"
                        },
                        new
                        {
                            Id = 58L,
                            ImageUrl = "mening-gevoel.jpg",
                            Name = "Mening / gevoel"
                        },
                        new
                        {
                            Id = 59L,
                            ImageUrl = "nieuw-leven.jpg",
                            Name = "Nieuw leven"
                        },
                        new
                        {
                            Id = 60L,
                            ImageUrl = "wie-ben-jij.jpg",
                            Name = "Wie ben jij?"
                        },
                        new
                        {
                            Id = 61L,
                            ImageUrl = "cijfers.jpg",
                            Name = "Cijfers"
                        },
                        new
                        {
                            Id = 62L,
                            ImageUrl = "het-weer.png",
                            Name = "Het weer"
                        },
                        new
                        {
                            Id = 63L,
                            ImageUrl = "tijd.jpg",
                            Name = "Tijd"
                        },
                        new
                        {
                            Id = 64L,
                            ImageUrl = "school.jpg",
                            Name = "School"
                        },
                        new
                        {
                            Id = 65L,
                            ImageUrl = "plaatsen.jpg",
                            Name = "Plaatsen / Ga je mee"
                        },
                        new
                        {
                            Id = 66L,
                            ImageUrl = "afspraak.jpg",
                            Name = "Afspraak"
                        });
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoryId");

                    b.Property<int>("Level");

                    b.Property<string>("Name");

                    b.Property<string>("QuestionUrl");

                    b.Property<string>("Title");

                    b.Property<string>("Type");

                    b.Property<string>("VideoUrl");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            Level = 0,
                            QuestionUrl = "hoe_laat_komt_de_bus.mp3",
                            Title = "Oefening 1",
                            Type = "true or false"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 1L,
                            Level = 1,
                            QuestionUrl = "kijk_naar_de_video_juist_of_out.wav",
                            Title = "Oefening 2",
                            Type = "true or false",
                            VideoUrl = "https://www.youtube.com/embed/h1zaAu_7VR0"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 1L,
                            Level = 2,
                            QuestionUrl = "ikZoekEenAppelVraag.mp3",
                            Title = "Oefening 3",
                            Type = "collage",
                            VideoUrl = "https://www.youtube.com/embed/7btgD5cJxnY"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 1L,
                            Level = 2,
                            QuestionUrl = "multiple_choice_question.mp3",
                            Title = "Oefening 4",
                            Type = "multiple choice",
                            VideoUrl = "https://www.youtube.com/embed/7btgD5cJxnY"
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 1L,
                            Level = 2,
                            QuestionUrl = "multiple_choice_question.mp3",
                            Title = "Oefening 5",
                            Type = "multiple choice"
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 1L,
                            Level = 1,
                            QuestionUrl = "wieBenJijAudio1.wav",
                            Title = "Oefening 6",
                            Type = "multiple choice"
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 1L,
                            Level = 0,
                            QuestionUrl = "wieBenJijAudio1.wav",
                            Title = "Oefening 7",
                            Type = "multiple choice"
                        });
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.ExerciseSeries", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("ExerciseSeries");
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<string>("Role");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            PasswordHash = new byte[] { 123, 133, 218, 252, 25, 103, 85, 105, 11, 237, 43, 164, 5, 159, 134, 10, 105, 186, 96, 67, 94, 51, 239, 10, 103, 51, 56, 13, 141, 90, 220, 86, 134, 211, 196, 37, 169, 83, 3, 182, 65, 206, 186, 69, 78, 40, 252, 42, 121, 165, 231, 251, 98, 236, 104, 243, 163, 121, 180, 220, 188, 101, 229, 116 },
                            PasswordSalt = new byte[] { 145, 124, 36, 189, 93, 32, 248, 179, 75, 31, 12, 220, 234, 227, 31, 105, 173, 116, 114, 108, 204, 225, 201, 88, 132, 254, 243, 157, 102, 95, 15, 46, 10, 152, 239, 107, 4, 40, 30, 240, 168, 170, 184, 50, 165, 76, 210, 14, 229, 11, 13, 31, 79, 43, 200, 8, 40, 171, 14, 94, 234, 83, 66, 115, 130, 36, 34, 119, 22, 148, 171, 214, 70, 44, 108, 182, 53, 189, 37, 76, 114, 91, 101, 211, 11, 210, 161, 66, 215, 177, 116, 248, 199, 53, 75, 144, 167, 255, 40, 35, 86, 13, 145, 246, 86, 174, 122, 193, 47, 96, 79, 67, 145, 174, 174, 244, 66, 101, 167, 26, 153, 35, 207, 241, 223, 151, 33, 46 },
                            Role = "Admin",
                            Username = "admin@limino.be"
                        },
                        new
                        {
                            Id = 2L,
                            PasswordHash = new byte[] { 123, 133, 218, 252, 25, 103, 85, 105, 11, 237, 43, 164, 5, 159, 134, 10, 105, 186, 96, 67, 94, 51, 239, 10, 103, 51, 56, 13, 141, 90, 220, 86, 134, 211, 196, 37, 169, 83, 3, 182, 65, 206, 186, 69, 78, 40, 252, 42, 121, 165, 231, 251, 98, 236, 104, 243, 163, 121, 180, 220, 188, 101, 229, 116 },
                            PasswordSalt = new byte[] { 145, 124, 36, 189, 93, 32, 248, 179, 75, 31, 12, 220, 234, 227, 31, 105, 173, 116, 114, 108, 204, 225, 201, 88, 132, 254, 243, 157, 102, 95, 15, 46, 10, 152, 239, 107, 4, 40, 30, 240, 168, 170, 184, 50, 165, 76, 210, 14, 229, 11, 13, 31, 79, 43, 200, 8, 40, 171, 14, 94, 234, 83, 66, 115, 130, 36, 34, 119, 22, 148, 171, 214, 70, 44, 108, 182, 53, 189, 37, 76, 114, 91, 101, 211, 11, 210, 161, 66, 215, 177, 116, 248, 199, 53, 75, 144, 167, 255, 40, 35, 86, 13, 145, 246, 86, 174, 122, 193, 47, 96, 79, 67, 145, 174, 174, 244, 66, 101, 167, 26, 153, 35, 207, 241, 223, 151, 33, 46 },
                            Role = "User",
                            Username = "teacher@limino.be"
                        });
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.Video", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CategoryId");

                    b.Property<string>("Name");

                    b.Property<string>("VideoUrl");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = 11L,
                            CategoryId = 1L,
                            Name = "Wie ben jij?",
                            VideoUrl = "https://www.youtube.com/embed/kvH9wlNrUTY"
                        },
                        new
                        {
                            Id = 12L,
                            CategoryId = 1L,
                            Name = "Cijfers",
                            VideoUrl = "https://www.youtube.com/embed/sHak0nIUsIQ"
                        },
                        new
                        {
                            Id = 13L,
                            CategoryId = 1L,
                            Name = "Het weer",
                            VideoUrl = "https://www.youtube.com/embed/1o_-LS34ntQ"
                        },
                        new
                        {
                            Id = 14L,
                            CategoryId = 1L,
                            Name = "Tijd",
                            VideoUrl = "https://www.youtube.com/embed/kvH9wlNrUTY"
                        },
                        new
                        {
                            Id = 15L,
                            CategoryId = 1L,
                            Name = "School",
                            VideoUrl = "https://www.youtube.com/embed/ZiOxgo5HbQM"
                        },
                        new
                        {
                            Id = 16L,
                            CategoryId = 1L,
                            Name = "Plaatsen / Ga je mee",
                            VideoUrl = "https://www.youtube.com/embed/w_nNIU88aVI"
                        },
                        new
                        {
                            Id = 17L,
                            CategoryId = 1L,
                            Name = "Afspraak",
                            VideoUrl = "https://www.youtube.com/embed/YXld4SDT2X4"
                        },
                        new
                        {
                            Id = 18L,
                            CategoryId = 1L,
                            Name = "Vragen",
                            VideoUrl = "https://www.youtube.com/embed/h1zaAu_7VR0"
                        },
                        new
                        {
                            Id = 19L,
                            CategoryId = 1L,
                            Name = "Eten en drinken",
                            VideoUrl = "https://www.youtube.com/embed/7btgD5cJxnY"
                        });
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.Answer", b =>
                {
                    b.HasOne("LiminoAPI.Data.Models.Exercise", "Exercise")
                        .WithMany("Answers")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.Audio", b =>
                {
                    b.HasOne("LiminoAPI.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.Exercise", b =>
                {
                    b.HasOne("LiminoAPI.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("LiminoAPI.Data.Models.Video", b =>
                {
                    b.HasOne("LiminoAPI.Data.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
